from __future__ import annotations

from typing import Any, Dict

from ..schemas import AssetRef, PeriodRef
from .base import BaseGenerator

MAJORS = [
    "The Fool", "The Magician", "The High Priestess", "The Empress", "The Emperor",
    "The Hierophant", "The Lovers", "The Chariot", "Strength", "The Hermit",
    "Wheel of Fortune", "Justice", "The Hanged Man", "Death", "Temperance",
    "The Devil", "The Tower", "The Star", "The Moon", "The Sun", "Judgement", "The World",
]
SUITS = ("Wands", "Cups", "Swords", "Pentacles")
RANKS = ("Ace", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Page", "Knight", "Queen", "King")
POSITIONS = [
    "Present", "Crossing", "Root", "Past", "Goal", "Near Future", "You",
    "Environment", "Hopes & Fears", "Outcome",
]


class TarotGenerator(BaseGenerator):
    engine_id = "tarot"

    def generate(self, asset: AssetRef, period: PeriodRef, market_context: Dict[str, Any], seed: int | None = None) -> Dict[str, Any]:
        rng = self.rng(asset, period, seed)
        deck = MAJORS + [f"{rank} of {suit}" for suit in SUITS for rank in RANKS]
        rng.shuffle(deck)
        spread = []
        for position, card in zip(POSITIONS, deck[:10]):
            spread.append({
                "position": position,
                "card": card,
                "orientation": "upright" if rng.random() >= 0.38 else "reversed",
            })
        artifact = self.base_artifact(asset, period, market_context, seed)
        artifact.update({
            "sop": "Celtic Cross, ten cards, generated by Python RNG before interpretation",
            "question": f"{asset.ticker} market tendency during {period.label}",
            "deck_size": len(deck),
            "spread_type": "celtic_cross",
            "spread": spread,
        })
        return artifact
